[package]
name = "dlopen_derive"
version = "0.1.4"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]
description = "Derive macros for the dlopen crate."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.34"
quote = "0.6.12"
libc = "0.2.29"

